sudo: false
language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc-4.9
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'cmake', 'cmake-data', 'zlib1g-dev', 'libbz2-dev', 'libboost-dev', 'python', 'python-nose', 'python-jinja2', 'python-pip']
      install: export CXX="g++-4.9"
      env: CMAKE_ARGS="-DGENMAP_STATIC_BUILD=1"

    - os: linux
      compiler: gcc-5
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'cmake', 'cmake-data', 'zlib1g-dev', 'libbz2-dev', 'libboost-dev', 'python', 'python-nose', 'python-jinja2', 'python-pip']
      install: export CXX="g++-5"
      env: CMAKE_ARGS="-DGENMAP_MULTIOPT_BUILD=1"

    - os: linux
      compiler: gcc-7
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'cmake', 'cmake-data', 'zlib1g-dev', 'libbz2-dev', 'libboost-dev', 'python', 'python-nose', 'python-jinja2', 'python-pip']
      install: export CXX="g++-7"
      env: CMAKE_ARGS="-DCMAKE_CXX_FLAGS=-std=c++17"

    - os: linux
      compiler: clang-3.9
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.9']
          packages: ['clang-3.9', 'g++-7', 'cmake', 'cmake-data', 'zlib1g-dev', 'libbz2-dev', 'libboost-dev', 'python', 'python-nose', 'python-jinja2', 'python-pip'] # g++ required for newer libstdc++
      install: export CXX="clang++-3.9"

    - os: linux
      compiler: clang-5
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'cmake', 'cmake-data', 'zlib1g-dev', 'libbz2-dev', 'libboost-dev', 'python', 'python-nose', 'python-jinja2', 'python-pip'] # g++ required for newer libstdc++
      install: export CXX="/usr/local/clang-5.0.0/bin/clang++"
      env: CMAKE_ARGS="-DCMAKE_BUILD_TYPE=RelWithDebInfo" LD_LIBRARY_PATH="/usr/local/clang-5.0.0/lib/:${LD_LIBRARY_PATH}"

    - os: osx
      compiler: gcc-4.9
      before_install:
        - brew update
        - brew install gcc@4.9
      install: export CXX="g++-4.9"
      env: CMAKE_ARGS="-DGENMAP_STATIC_BUILD=1"

    - os: osx
      compiler: gcc-7
      before_install:
        - brew update
        - brew install gcc@7
      install: export CXX="g++-7"
      env: CMAKE_ARGS=""

script:
  - mkdir -p build && cd build
  - cmake .. -DGENMAP_NATIVE_BUILD=0 -DGENMAP_COMPILE_THREADS=2 ${CMAKE_ARGS}
  - travis_wait make VERBOSE=1
  # - ctest .
